### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by mishal23** [berkmancenter/question_tool#101]
Hi, I tried setting up the project locally, and on running `npm install` in the directory `programs/server`, I am facing this error. Any help would be appreciated.
```
OS: Ubuntu 18.04
Node version: v9.11.2
npm version: 6.4.1
meteor version: 1.4.1.1
```

```
> fibers@1.0.13 install /home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:49:34: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template type
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                  ^~~~~~~~~~~~~~~~
../src/fibers.cc:49:50: error: expected ‘,’ or ‘...’ before ‘<’ token
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                                  ^
../src/fibers.cc: In function ‘void uni::WeakCallbackShim(int)’:
../src/fibers.cc:50:5: error: ‘data’ was not declared in this scope
   F(data.GetParameter());
     ^~~~
../src/fibers.cc: In function ‘v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)’:
../src/fibers.cc:102:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:2731:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In function ‘v8::Handle<v8::String> uni::NewLatin1Symbol(v8::Isolate*, const char*)’:
../src/fibers.cc:106:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:2731:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::New(const Arguments&)’:
../src/fibers.cc:423:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                   ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3894:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static void Fiber::RunFiber(void**)’:
../src/fibers.cc:611:14: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^~~~~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:8394:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’:
../src/fibers.cc:731:43: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    Coroutine::pool_size = value->ToNumber()->Value();
                                           ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:9853:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/fibers.cc: In static member function ‘static void Fiber::Init(v8::Handle<v8::Object>)’:
../src/fibers.cc:785:72: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                                                                        ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc:786:87: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                       ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc:787:84: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In instantiation of ‘void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*) [with void (* F)(void*) = Fiber::WeakCallback; T = v8::Object; P = void]’:
../src/fibers.cc:341:60:   required from here
../src/fibers.cc:55:3: error: no matching function for call to ‘v8::Persistent<v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)’
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:546:18: note: candidate: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
   V8_INLINE void SetWeak(P* parameter,
                  ^~~~~~~
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:546:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:55:3: note:   candidate expects 3 arguments, 2 provided
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:557:18: note: candidate: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
   V8_INLINE void SetWeak();
                  ^~~~~~~
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:557:18: note:   candidate expects 0 arguments, 2 provided
fibers.target.mk:108: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
make: Entering directory '/home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:49:34: error: ‘WeakCallbackData’ in namespace ‘v8’ does not name a template type
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                  ^~~~~~~~~~~~~~~~
../src/fibers.cc:49:50: error: expected ‘,’ or ‘...’ before ‘<’ token
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                                  ^
../src/fibers.cc: In function ‘void uni::WeakCallbackShim(int)’:
../src/fibers.cc:50:5: error: ‘data’ was not declared in this scope
   F(data.GetParameter());
     ^~~~
../src/fibers.cc: In function ‘v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)’:
../src/fibers.cc:102:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:2731:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In function ‘v8::Handle<v8::String> uni::NewLatin1Symbol(v8::Isolate*, const char*)’:
../src/fibers.cc:106:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:2731:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::New(const Arguments&)’:
../src/fibers.cc:423:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                   ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3894:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static void Fiber::RunFiber(void**)’:
../src/fibers.cc:611:14: warning: ‘v8::TryCatch::TryCatch()’ is deprecated: Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^~~~~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:8394:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In static member function ‘static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’:
../src/fibers.cc:731:43: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    Coroutine::pool_size = value->ToNumber()->Value();
                                           ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:9853:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^~~~~
../src/fibers.cc: In static member function ‘static void Fiber::Init(v8::Handle<v8::Object>)’:
../src/fibers.cc:785:72: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                                                                        ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc:786:87: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                       ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc:787:84: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:3227:22: note: declared here
                 bool SetAccessor(Local<String> name,
                      ^
/home/mishal23/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/fibers.cc: In instantiation of ‘void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*) [with void (* F)(void*) = Fiber::WeakCallback; T = v8::Object; P = void]’:
../src/fibers.cc:341:60:   required from here
../src/fibers.cc:55:3: error: no matching function for call to ‘v8::Persistent<v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)’
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:546:18: note: candidate: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
   V8_INLINE void SetWeak(P* parameter,
                  ^~~~~~~
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:546:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:55:3: note:   candidate expects 3 arguments, 2 provided
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^~~~~~
In file included from /home/mishal23/.node-gyp/9.11.2/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:557:18: note: candidate: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
   V8_INLINE void SetWeak();
                  ^~~~~~~
/home/mishal23/.node-gyp/9.11.2/include/node/v8.h:557:18: note:   candidate expects 0 arguments, 2 provided
fibers.target.mk:108: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/mishal23/Projects/GSOC/berkmancenter/question_tool/build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v9.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++`
Alpine users please run: `sudo apk add python make g++`
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mishal23/.npm/_logs/2019-03-03T12_08_05_321Z-debug.log
```

**Comment by Salil-Jain** [comment]
Hi, @mishal23 Have a look at #76. I think it's similar

**Comment by nanspro** [comment]
@Salil-Jain  are you a maintainer. I have send you mail introducing myself and with some questions regarding the project.
