### ISSUE TITLE
Changes in Installation guidelines required

### ISSUE THREAD

**Issue by chaitanyagiri** [berkmancenter/question_tool#71]
I have been trying to install this on my computer for a while and I am facing some issues.

- The version of MeteorJS to be used is not defined(probably 1.4.2.1).
- Node's version should be less than or equal to 6.
- External installation of babel-runtime is required to resolve the error(Most probably) [refer this](https://github.com/meteor/meteor/issues/7833).
- Also, installation of meteor behind a proxy server might create an error(It did in my case).

PS - I am still not successful in installing it but these changes will help any newcomer.

**Comment by jsdiaz** [comment]
Hi Chaitanya, the current dev version is running meteor v1.4.1.1 and node v4.4.7.

I'm not sure of the error that you are referring to in your third bullet point, but we are running the current dev version behind a proxy and there are no issues.

**Comment by chaitanyagiri** [comment]
@jsdiaz , thanks for the help. Previous errors were solved however some new errors related to MongoDB occurred the error is something like this:
```
/question_tool/{output_dir}/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: $MONGO_OPLOG_URL must be set to the 'local' database of a Mongo replica set
    at Error (native)
    at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:218:13)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
    at new MongoConnection (packages/mongo/mongo_driver.js:219:25)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)

```
If possible please help me resolve it.
